version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/interview-prep-ai
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5009:5009"
    env_file:
      - ./backend/.env